apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: second-

patches:
  - path: cores.yaml
    target:
      kind: VirtualMachine
  - path: disk.yaml
    target:
      kind: VirtualMachine

resources:
  - ../../base/
