apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm
  labels:
    app: vms
  annotations:
    vm.kubevirt.io/validations: |
      [
        {
          "name": "minimal-required-memory",
          "path": "jsonpath::.spec.domain.memory.guest",
          "rule": "integer",
          "message": "This VM requires more memory.",
          "min": 1610612736
        }
      ]
spec:
  runStrategy: RerunOnFailure
  template:
    spec:
      domain:
        cpu:
          sockets: 1
          cores: 1
          threads: 1
        memory:
          guest: 2Gi
        devices:
          rng: {}
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
        resources: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          dataVolume:
            name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: changemenow!
              chpasswd: { expire: False }
          name: cloudinitdisk
  dataVolumeTemplates:
    - metadata:
        name: rootdisk
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
